### Flujo de Pruebas

###
echo "###############################\nObtener la Cadena..."
curl http://localhost:5000/get_chain

###
echo "###############################\nMinar bloque nuevo 1..."
curl http://localhost:5000/mine_block

###
echo "###############################\nMinar bloque nuevo 2..."
curl http://localhost:5000/mine_block

###
echo "###############################\nObtener la Cadena, debe entregar los bloques minados (3 en total)..."
curl http://localhost:5000/get_chain

###
echo "###############################\nValidar la Cadena, debe ser válida..."
curl http://localhost:5000/is_valid

### 
echo "###############################\nMinar un bloque MALO..."
curl http://localhost:5000/add_bad_block

### 
echo "###############################\nObtener la Cadena, debe entregar los bloques minados, más el bloque MALO..."
curl http://localhost:5000/get_chain

###
echo "###############################\nValidar la Cadena, debe indicar que la cadena no es válida..."
curl http://localhost:5000/is_valid
